spring:
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  redis:
    password: 123456
server:
  port: 8080
  contextPath: /view/thymeleaf
  